# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpaste', '0002_auto_20170119_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lexer',
            field=models.CharField(default='python', max_length=30, verbose_name='Lexer'),
        ),
    ]
